// ─── Role Category Config ─────────────────────────────────────────────────────
// Pure data/config — no React or component imports.
// Icons are referenced by string name; the consuming component maps them to
// actual Lucide (or other) components.
//
// Color palette convention:
//   Primary lane  → blue
//   Secondary     → emerald
//   Tertiary      → amber
//   Quaternary    → rose
//   Quinary       → violet (5th role-specific lane when present)
//   Senary        → teal   (6th role-specific lane when present)
//   Meetings      → cyan
//   Promotions    → purple
//   Do Not Reply  → slate

// ─── Types ────────────────────────────────────────────────────────────────────

/**
 * A single inbox lane as understood by SplitInbox (icon as a string name).
 * The consuming component is responsible for resolving the icon string to a
 * component.
 */
export interface LaneConfig {
  key: string;
  label: string;
  /** Icon identifier string — map to a Lucide component in the consumer. */
  icon: string;
  color: string;
  dot: string;
  border: string;
  bg: string;
  headerBg: string;
  /** Backend category strings that should be routed to this lane. */
  categories: string[];
}

export interface RoleConfig {
  key: string;
  name: string;
  emoji: string;
  lanes: LaneConfig[];
}

// ─── Shared lanes appended to every role ─────────────────────────────────────

const SHARED_PROMOTIONS_LANE: LaneConfig = {
  key: 'promotions',
  label: 'Promotions',
  icon: 'Tag',
  color: 'text-purple-400',
  dot: 'bg-purple-400',
  border: 'border-purple-500/25',
  bg: 'bg-purple-500/5',
  headerBg: 'bg-purple-500/10',
  categories: ['promotional', 'newsletter', 'marketing'],
};

const SHARED_DO_NOT_REPLY_LANE: LaneConfig = {
  key: 'donotreply',
  label: 'Do Not Reply',
  icon: 'BellOff',
  color: 'text-slate-400',
  dot: 'bg-slate-400',
  border: 'border-slate-500/25',
  bg: 'bg-slate-500/5',
  headerBg: 'bg-slate-500/10',
  categories: ['transactional', 'spam', 'social'],
};

/** Appends the two shared lanes (Promotions, Do Not Reply) to a lane list. */
function withShared(lanes: LaneConfig[]): LaneConfig[] {
  return [...lanes, SHARED_PROMOTIONS_LANE, SHARED_DO_NOT_REPLY_LANE];
}

// ─── Role Definitions ─────────────────────────────────────────────────────────

const ROLE_CONFIGS_MAP: Record<string, RoleConfig> = {
  // ── Student ──────────────────────────────────────────────────────────────
  student: {
    key: 'student',
    name: 'Student',
    emoji: '🎓',
    lanes: withShared([
      {
        key: 'academics',
        label: 'Academics',
        icon: 'BookOpen',
        color: 'text-blue-400',
        dot: 'bg-blue-400',
        border: 'border-blue-500/25',
        bg: 'bg-blue-500/5',
        headerBg: 'bg-blue-500/10',
        categories: [
          'assignment',
          'exam_notice',
          'faculty_communication',
          'study_group',
        ],
      },
      {
        key: 'career',
        label: 'Career',
        icon: 'Briefcase',
        color: 'text-emerald-400',
        dot: 'bg-emerald-400',
        border: 'border-emerald-500/25',
        bg: 'bg-emerald-500/5',
        headerBg: 'bg-emerald-500/10',
        categories: [
          'internship',
          'interview',
          'job_application',
          'scholarship',
        ],
      },
      {
        key: 'campus',
        label: 'Campus',
        icon: 'Building2',
        color: 'text-amber-400',
        dot: 'bg-amber-400',
        border: 'border-amber-500/25',
        bg: 'bg-amber-500/5',
        headerBg: 'bg-amber-500/10',
        categories: ['campus_event'],
      },
      {
        key: 'meetings',
        label: 'Meetings',
        icon: 'CalendarClock',
        color: 'text-cyan-400',
        dot: 'bg-cyan-400',
        border: 'border-cyan-500/25',
        bg: 'bg-cyan-500/5',
        headerBg: 'bg-cyan-500/10',
        categories: ['meeting_invitation'],
      },
    ]),
  },

  // ── Working Professional ──────────────────────────────────────────────────
  working_professional: {
    key: 'working_professional',
    name: 'Working Professional',
    emoji: '💼',
    lanes: withShared([
      {
        key: 'work',
        label: 'Work',
        icon: 'Briefcase',
        color: 'text-blue-400',
        dot: 'bg-blue-400',
        border: 'border-blue-500/25',
        bg: 'bg-blue-500/5',
        headerBg: 'bg-blue-500/10',
        categories: [
          'task_assigned',
          'deadline_reminder',
          'approval_required',
          'internal_update',
          'important',
        ],
      },
      {
        key: 'clients',
        label: 'Clients',
        icon: 'Users',
        color: 'text-emerald-400',
        dot: 'bg-emerald-400',
        border: 'border-emerald-500/25',
        bg: 'bg-emerald-500/5',
        headerBg: 'bg-emerald-500/10',
        categories: ['client_communication'],
      },
      {
        key: 'hr',
        label: 'HR',
        icon: 'UserCheck',
        color: 'text-amber-400',
        dot: 'bg-amber-400',
        border: 'border-amber-500/25',
        bg: 'bg-amber-500/5',
        headerBg: 'bg-amber-500/10',
        categories: ['hr_update', 'interview', 'training'],
      },
      {
        key: 'meetings',
        label: 'Meetings',
        icon: 'CalendarClock',
        color: 'text-cyan-400',
        dot: 'bg-cyan-400',
        border: 'border-cyan-500/25',
        bg: 'bg-cyan-500/5',
        headerBg: 'bg-cyan-500/10',
        categories: ['meeting_invitation'],
      },
    ]),
  },

  // ── Founder ───────────────────────────────────────────────────────────────
  founder: {
    key: 'founder',
    name: 'Founder',
    emoji: '🚀',
    lanes: withShared([
      {
        key: 'investors',
        label: 'Investors',
        icon: 'TrendingUp',
        color: 'text-blue-400',
        dot: 'bg-blue-400',
        border: 'border-blue-500/25',
        bg: 'bg-blue-500/5',
        headerBg: 'bg-blue-500/10',
        categories: ['investor_communication', 'fundraising'],
      },
      {
        key: 'customers',
        label: 'Customers',
        icon: 'Users',
        color: 'text-emerald-400',
        dot: 'bg-emerald-400',
        border: 'border-emerald-500/25',
        bg: 'bg-emerald-500/5',
        headerBg: 'bg-emerald-500/10',
        categories: ['customer_feedback'],
      },
      {
        key: 'business',
        label: 'Business',
        icon: 'Briefcase',
        color: 'text-amber-400',
        dot: 'bg-amber-400',
        border: 'border-amber-500/25',
        bg: 'bg-amber-500/5',
        headerBg: 'bg-amber-500/10',
        categories: [
          'partnership',
          'hiring',
          'press_media',
          'product_update',
        ],
      },
      {
        key: 'legal',
        label: 'Legal',
        icon: 'Scale',
        color: 'text-rose-400',
        dot: 'bg-rose-400',
        border: 'border-rose-500/25',
        bg: 'bg-rose-500/5',
        headerBg: 'bg-rose-500/10',
        categories: ['legal_compliance'],
      },
      {
        key: 'cold_outreach',
        label: 'Cold Outreach',
        icon: 'Mail',
        color: 'text-violet-400',
        dot: 'bg-violet-400',
        border: 'border-violet-500/25',
        bg: 'bg-violet-500/5',
        headerBg: 'bg-violet-500/10',
        categories: ['cold_outreach'],
      },
      {
        key: 'meetings',
        label: 'Meetings',
        icon: 'CalendarClock',
        color: 'text-cyan-400',
        dot: 'bg-cyan-400',
        border: 'border-cyan-500/25',
        bg: 'bg-cyan-500/5',
        headerBg: 'bg-cyan-500/10',
        categories: ['meeting_invitation'],
      },
    ]),
  },

  // ── Influencer ────────────────────────────────────────────────────────────
  influencer: {
    key: 'influencer',
    name: 'Influencer',
    emoji: '✨',
    lanes: withShared([
      {
        key: 'brand_deals',
        label: 'Brand Deals',
        icon: 'Star',
        color: 'text-blue-400',
        dot: 'bg-blue-400',
        border: 'border-blue-500/25',
        bg: 'bg-blue-500/5',
        headerBg: 'bg-blue-500/10',
        categories: ['brand_deal', 'deliverable_request'],
      },
      {
        key: 'agency',
        label: 'Agency',
        icon: 'Building2',
        color: 'text-emerald-400',
        dot: 'bg-emerald-400',
        border: 'border-emerald-500/25',
        bg: 'bg-emerald-500/5',
        headerBg: 'bg-emerald-500/10',
        categories: ['agency_communication'],
      },
      {
        key: 'collabs',
        label: 'Collabs',
        icon: 'Handshake',
        color: 'text-amber-400',
        dot: 'bg-amber-400',
        border: 'border-amber-500/25',
        bg: 'bg-amber-500/5',
        headerBg: 'bg-amber-500/10',
        categories: ['collab_request'],
      },
      {
        key: 'payments',
        label: 'Payments',
        icon: 'Banknote',
        color: 'text-rose-400',
        dot: 'bg-rose-400',
        border: 'border-rose-500/25',
        bg: 'bg-rose-500/5',
        headerBg: 'bg-rose-500/10',
        categories: ['payment'],
      },
      {
        key: 'platform',
        label: 'Platform',
        icon: 'MonitorSmartphone',
        color: 'text-violet-400',
        dot: 'bg-violet-400',
        border: 'border-violet-500/25',
        bg: 'bg-violet-500/5',
        headerBg: 'bg-violet-500/10',
        categories: ['platform_update', 'event_invite'],
      },
      {
        key: 'meetings',
        label: 'Meetings',
        icon: 'CalendarClock',
        color: 'text-cyan-400',
        dot: 'bg-cyan-400',
        border: 'border-cyan-500/25',
        bg: 'bg-cyan-500/5',
        headerBg: 'bg-cyan-500/10',
        categories: ['meeting_invitation'],
      },
    ]),
  },

  // ── Freelancer ────────────────────────────────────────────────────────────
  freelancer: {
    key: 'freelancer',
    name: 'Freelancer',
    emoji: '🧑‍💻',
    lanes: withShared([
      {
        key: 'projects',
        label: 'Projects',
        icon: 'FolderOpen',
        color: 'text-blue-400',
        dot: 'bg-blue-400',
        border: 'border-blue-500/25',
        bg: 'bg-blue-500/5',
        headerBg: 'bg-blue-500/10',
        categories: [
          'new_project_inquiry',
          'client_communication',
          'revision_request',
        ],
      },
      {
        key: 'payments',
        label: 'Payments',
        icon: 'Banknote',
        color: 'text-emerald-400',
        dot: 'bg-emerald-400',
        border: 'border-emerald-500/25',
        bg: 'bg-emerald-500/5',
        headerBg: 'bg-emerald-500/10',
        categories: ['invoice_payment', 'contract'],
      },
      {
        key: 'platform',
        label: 'Platform',
        icon: 'MonitorSmartphone',
        color: 'text-amber-400',
        dot: 'bg-amber-400',
        border: 'border-amber-500/25',
        bg: 'bg-amber-500/5',
        headerBg: 'bg-amber-500/10',
        categories: ['platform_notification', 'deadline_reminder'],
      },
      {
        key: 'meetings',
        label: 'Meetings',
        icon: 'CalendarClock',
        color: 'text-cyan-400',
        dot: 'bg-cyan-400',
        border: 'border-cyan-500/25',
        bg: 'bg-cyan-500/5',
        headerBg: 'bg-cyan-500/10',
        categories: ['meeting_invitation'],
      },
    ]),
  },

  // ── Business Owner ────────────────────────────────────────────────────────
  business_owner: {
    key: 'business_owner',
    name: 'Business Owner',
    emoji: '🏢',
    lanes: withShared([
      {
        key: 'suppliers',
        label: 'Suppliers',
        icon: 'Truck',
        color: 'text-blue-400',
        dot: 'bg-blue-400',
        border: 'border-blue-500/25',
        bg: 'bg-blue-500/5',
        headerBg: 'bg-blue-500/10',
        categories: ['vendor_supplier'],
      },
      {
        key: 'orders',
        label: 'Orders',
        icon: 'ShoppingCart',
        color: 'text-emerald-400',
        dot: 'bg-emerald-400',
        border: 'border-emerald-500/25',
        bg: 'bg-emerald-500/5',
        headerBg: 'bg-emerald-500/10',
        categories: ['customer_order'],
      },
      {
        key: 'finance',
        label: 'Finance',
        icon: 'Landmark',
        color: 'text-amber-400',
        dot: 'bg-amber-400',
        border: 'border-amber-500/25',
        bg: 'bg-amber-500/5',
        headerBg: 'bg-amber-500/10',
        categories: ['financial'],
      },
      {
        key: 'staff',
        label: 'Staff',
        icon: 'UserCheck',
        color: 'text-rose-400',
        dot: 'bg-rose-400',
        border: 'border-rose-500/25',
        bg: 'bg-rose-500/5',
        headerBg: 'bg-rose-500/10',
        categories: ['staff_hr'],
      },
      {
        key: 'legal',
        label: 'Legal',
        icon: 'Scale',
        color: 'text-violet-400',
        dot: 'bg-violet-400',
        border: 'border-violet-500/25',
        bg: 'bg-violet-500/5',
        headerBg: 'bg-violet-500/10',
        categories: ['legal_compliance', 'partnership'],
      },
      {
        key: 'ops',
        label: 'Ops',
        icon: 'Settings2',
        color: 'text-teal-400',
        dot: 'bg-teal-400',
        border: 'border-teal-500/25',
        bg: 'bg-teal-500/5',
        headerBg: 'bg-teal-500/10',
        categories: ['operations', 'marketing'],
      },
      {
        key: 'meetings',
        label: 'Meetings',
        icon: 'CalendarClock',
        color: 'text-cyan-400',
        dot: 'bg-cyan-400',
        border: 'border-cyan-500/25',
        bg: 'bg-cyan-500/5',
        headerBg: 'bg-cyan-500/10',
        categories: ['meeting_invitation'],
      },
    ]),
  },

  // ── Healthcare ────────────────────────────────────────────────────────────
  healthcare: {
    key: 'healthcare',
    name: 'Healthcare',
    emoji: '🏥',
    lanes: withShared([
      {
        key: 'patients',
        label: 'Patients',
        icon: 'HeartPulse',
        color: 'text-blue-400',
        dot: 'bg-blue-400',
        border: 'border-blue-500/25',
        bg: 'bg-blue-500/5',
        headerBg: 'bg-blue-500/10',
        categories: ['patient_communication', 'prescription_refill'],
      },
      {
        key: 'lab',
        label: 'Lab',
        icon: 'FlaskConical',
        color: 'text-emerald-400',
        dot: 'bg-emerald-400',
        border: 'border-emerald-500/25',
        bg: 'bg-emerald-500/5',
        headerBg: 'bg-emerald-500/10',
        categories: ['lab_results'],
      },
      {
        key: 'research',
        label: 'Research',
        icon: 'Microscope',
        color: 'text-amber-400',
        dot: 'bg-amber-400',
        border: 'border-amber-500/25',
        bg: 'bg-amber-500/5',
        headerBg: 'bg-amber-500/10',
        categories: ['clinical_trial', 'peer_review'],
      },
      {
        key: 'admin',
        label: 'Admin',
        icon: 'ClipboardList',
        color: 'text-rose-400',
        dot: 'bg-rose-400',
        border: 'border-rose-500/25',
        bg: 'bg-rose-500/5',
        headerBg: 'bg-rose-500/10',
        categories: ['admin_compliance', 'pharma_update'],
      },
      {
        key: 'cme',
        label: 'CME',
        icon: 'GraduationCap',
        color: 'text-violet-400',
        dot: 'bg-violet-400',
        border: 'border-violet-500/25',
        bg: 'bg-violet-500/5',
        headerBg: 'bg-violet-500/10',
        categories: ['conference_cme'],
      },
      {
        key: 'meetings',
        label: 'Meetings',
        icon: 'CalendarClock',
        color: 'text-cyan-400',
        dot: 'bg-cyan-400',
        border: 'border-cyan-500/25',
        bg: 'bg-cyan-500/5',
        headerBg: 'bg-cyan-500/10',
        categories: ['meeting_invitation'],
      },
    ]),
  },

  // ── Legal ─────────────────────────────────────────────────────────────────
  legal: {
    key: 'legal',
    name: 'Legal',
    emoji: '⚖️',
    lanes: withShared([
      {
        key: 'cases',
        label: 'Cases',
        icon: 'Gavel',
        color: 'text-blue-400',
        dot: 'bg-blue-400',
        border: 'border-blue-500/25',
        bg: 'bg-blue-500/5',
        headerBg: 'bg-blue-500/10',
        categories: ['case_update', 'opposing_counsel', 'court_notice'],
      },
      {
        key: 'clients',
        label: 'Clients',
        icon: 'Users',
        color: 'text-emerald-400',
        dot: 'bg-emerald-400',
        border: 'border-emerald-500/25',
        bg: 'bg-emerald-500/5',
        headerBg: 'bg-emerald-500/10',
        categories: ['client_communication', 'document_review'],
      },
      {
        key: 'billing',
        label: 'Billing',
        icon: 'Receipt',
        color: 'text-amber-400',
        dot: 'bg-amber-400',
        border: 'border-amber-500/25',
        bg: 'bg-amber-500/5',
        headerBg: 'bg-amber-500/10',
        categories: ['billing_invoice'],
      },
      {
        key: 'research',
        label: 'Research',
        icon: 'BookOpen',
        color: 'text-rose-400',
        dot: 'bg-rose-400',
        border: 'border-rose-500/25',
        bg: 'bg-rose-500/5',
        headerBg: 'bg-rose-500/10',
        categories: ['legal_research', 'bar_association'],
      },
      {
        key: 'meetings',
        label: 'Meetings',
        icon: 'CalendarClock',
        color: 'text-cyan-400',
        dot: 'bg-cyan-400',
        border: 'border-cyan-500/25',
        bg: 'bg-cyan-500/5',
        headerBg: 'bg-cyan-500/10',
        categories: ['meeting_invitation'],
      },
    ]),
  },

  // ── Educator ──────────────────────────────────────────────────────────────
  educator: {
    key: 'educator',
    name: 'Educator',
    emoji: '📚',
    lanes: withShared([
      {
        key: 'students',
        label: 'Students',
        icon: 'GraduationCap',
        color: 'text-blue-400',
        dot: 'bg-blue-400',
        border: 'border-blue-500/25',
        bg: 'bg-blue-500/5',
        headerBg: 'bg-blue-500/10',
        categories: ['student_communication', 'exam_grading'],
      },
      {
        key: 'parents',
        label: 'Parents',
        icon: 'Users',
        color: 'text-emerald-400',
        dot: 'bg-emerald-400',
        border: 'border-emerald-500/25',
        bg: 'bg-emerald-500/5',
        headerBg: 'bg-emerald-500/10',
        categories: ['parent_communication'],
      },
      {
        key: 'admin',
        label: 'Admin',
        icon: 'ClipboardList',
        color: 'text-amber-400',
        dot: 'bg-amber-400',
        border: 'border-amber-500/25',
        bg: 'bg-amber-500/5',
        headerBg: 'bg-amber-500/10',
        categories: ['admin_directive', 'training_pd'],
      },
      {
        key: 'research',
        label: 'Research',
        icon: 'Microscope',
        color: 'text-rose-400',
        dot: 'bg-rose-400',
        border: 'border-rose-500/25',
        bg: 'bg-rose-500/5',
        headerBg: 'bg-rose-500/10',
        categories: ['research', 'conference', 'peer_review'],
      },
      {
        key: 'meetings',
        label: 'Meetings',
        icon: 'CalendarClock',
        color: 'text-cyan-400',
        dot: 'bg-cyan-400',
        border: 'border-cyan-500/25',
        bg: 'bg-cyan-500/5',
        headerBg: 'bg-cyan-500/10',
        categories: ['meeting_invitation'],
      },
    ]),
  },

  // ── Trades ────────────────────────────────────────────────────────────────
  trades: {
    key: 'trades',
    name: 'Trades',
    emoji: '🔧',
    lanes: withShared([
      {
        key: 'work_orders',
        label: 'Work Orders',
        icon: 'Wrench',
        color: 'text-blue-400',
        dot: 'bg-blue-400',
        border: 'border-blue-500/25',
        bg: 'bg-blue-500/5',
        headerBg: 'bg-blue-500/10',
        categories: ['work_order', 'site_update'],
      },
      {
        key: 'parts',
        label: 'Parts',
        icon: 'Package',
        color: 'text-emerald-400',
        dot: 'bg-emerald-400',
        border: 'border-emerald-500/25',
        bg: 'bg-emerald-500/5',
        headerBg: 'bg-emerald-500/10',
        categories: ['parts_procurement', 'vendor_supplier'],
      },
      {
        key: 'clients',
        label: 'Clients',
        icon: 'Users',
        color: 'text-amber-400',
        dot: 'bg-amber-400',
        border: 'border-amber-500/25',
        bg: 'bg-amber-500/5',
        headerBg: 'bg-amber-500/10',
        categories: ['client_site_communication'],
      },
      {
        key: 'safety',
        label: 'Safety',
        icon: 'ShieldCheck',
        color: 'text-rose-400',
        dot: 'bg-rose-400',
        border: 'border-rose-500/25',
        bg: 'bg-rose-500/5',
        headerBg: 'bg-rose-500/10',
        categories: ['compliance_safety', 'training'],
      },
      {
        key: 'billing',
        label: 'Billing',
        icon: 'Receipt',
        color: 'text-violet-400',
        dot: 'bg-violet-400',
        border: 'border-violet-500/25',
        bg: 'bg-violet-500/5',
        headerBg: 'bg-violet-500/10',
        categories: ['invoice_payment'],
      },
      {
        key: 'meetings',
        label: 'Meetings',
        icon: 'CalendarClock',
        color: 'text-cyan-400',
        dot: 'bg-cyan-400',
        border: 'border-cyan-500/25',
        bg: 'bg-cyan-500/5',
        headerBg: 'bg-cyan-500/10',
        categories: ['meeting_invitation'],
      },
    ]),
  },

  // ── Real Estate ───────────────────────────────────────────────────────────
  real_estate: {
    key: 'real_estate',
    name: 'Real Estate',
    emoji: '🏡',
    lanes: withShared([
      {
        key: 'listings',
        label: 'Listings',
        icon: 'Home',
        color: 'text-blue-400',
        dot: 'bg-blue-400',
        border: 'border-blue-500/25',
        bg: 'bg-blue-500/5',
        headerBg: 'bg-blue-500/10',
        categories: ['listing_inquiry', 'mls_update'],
      },
      {
        key: 'deals',
        label: 'Deals',
        icon: 'FileSignature',
        color: 'text-emerald-400',
        dot: 'bg-emerald-400',
        border: 'border-emerald-500/25',
        bg: 'bg-emerald-500/5',
        headerBg: 'bg-emerald-500/10',
        categories: ['offer_negotiation', 'escrow_legal'],
      },
      {
        key: 'clients',
        label: 'Clients',
        icon: 'Users',
        color: 'text-amber-400',
        dot: 'bg-amber-400',
        border: 'border-amber-500/25',
        bg: 'bg-amber-500/5',
        headerBg: 'bg-amber-500/10',
        categories: ['client_communication'],
      },
      {
        key: 'finance',
        label: 'Finance',
        icon: 'Landmark',
        color: 'text-rose-400',
        dot: 'bg-rose-400',
        border: 'border-rose-500/25',
        bg: 'bg-rose-500/5',
        headerBg: 'bg-rose-500/10',
        categories: ['lending_mortgage', 'commission_payment'],
      },
      {
        key: 'marketing',
        label: 'Marketing',
        icon: 'Megaphone',
        color: 'text-violet-400',
        dot: 'bg-violet-400',
        border: 'border-violet-500/25',
        bg: 'bg-violet-500/5',
        headerBg: 'bg-violet-500/10',
        categories: ['marketing'],
      },
      {
        key: 'meetings',
        label: 'Meetings',
        icon: 'CalendarClock',
        color: 'text-cyan-400',
        dot: 'bg-cyan-400',
        border: 'border-cyan-500/25',
        bg: 'bg-cyan-500/5',
        headerBg: 'bg-cyan-500/10',
        categories: ['meeting_invitation'],
      },
    ]),
  },

  // ── Nonprofit ─────────────────────────────────────────────────────────────
  nonprofit: {
    key: 'nonprofit',
    name: 'Nonprofit',
    emoji: '🤝',
    lanes: withShared([
      {
        key: 'donors',
        label: 'Donors',
        icon: 'Heart',
        color: 'text-blue-400',
        dot: 'bg-blue-400',
        border: 'border-blue-500/25',
        bg: 'bg-blue-500/5',
        headerBg: 'bg-blue-500/10',
        categories: ['donor_communication'],
      },
      {
        key: 'grants',
        label: 'Grants',
        icon: 'FileText',
        color: 'text-emerald-400',
        dot: 'bg-emerald-400',
        border: 'border-emerald-500/25',
        bg: 'bg-emerald-500/5',
        headerBg: 'bg-emerald-500/10',
        categories: ['grant_application', 'government_compliance'],
      },
      {
        key: 'volunteers',
        label: 'Volunteers',
        icon: 'Users',
        color: 'text-amber-400',
        dot: 'bg-amber-400',
        border: 'border-amber-500/25',
        bg: 'bg-amber-500/5',
        headerBg: 'bg-amber-500/10',
        categories: ['volunteer_coordination'],
      },
      {
        key: 'impact',
        label: 'Impact',
        icon: 'BarChart2',
        color: 'text-rose-400',
        dot: 'bg-rose-400',
        border: 'border-rose-500/25',
        bg: 'bg-rose-500/5',
        headerBg: 'bg-rose-500/10',
        categories: ['beneficiary_update', 'internal_update'],
      },
      {
        key: 'events',
        label: 'Events',
        icon: 'CalendarDays',
        color: 'text-violet-400',
        dot: 'bg-violet-400',
        border: 'border-violet-500/25',
        bg: 'bg-violet-500/5',
        headerBg: 'bg-violet-500/10',
        categories: ['event_fundraiser', 'partnership'],
      },
      {
        key: 'meetings',
        label: 'Meetings',
        icon: 'CalendarClock',
        color: 'text-cyan-400',
        dot: 'bg-cyan-400',
        border: 'border-cyan-500/25',
        bg: 'bg-cyan-500/5',
        headerBg: 'bg-cyan-500/10',
        categories: ['meeting_invitation'],
      },
    ]),
  },

  // ── Finance ───────────────────────────────────────────────────────────────
  finance: {
    key: 'finance',
    name: 'Finance',
    emoji: '📊',
    lanes: withShared([
      {
        key: 'audit',
        label: 'Audit',
        icon: 'ClipboardCheck',
        color: 'text-blue-400',
        dot: 'bg-blue-400',
        border: 'border-blue-500/25',
        bg: 'bg-blue-500/5',
        headerBg: 'bg-blue-500/10',
        categories: ['audit_compliance'],
      },
      {
        key: 'reports',
        label: 'Reports',
        icon: 'BarChart2',
        color: 'text-emerald-400',
        dot: 'bg-emerald-400',
        border: 'border-emerald-500/25',
        bg: 'bg-emerald-500/5',
        headerBg: 'bg-emerald-500/10',
        categories: ['client_financial_report', 'budget_planning'],
      },
      {
        key: 'tax',
        label: 'Tax',
        icon: 'FileText',
        color: 'text-amber-400',
        dot: 'bg-amber-400',
        border: 'border-amber-500/25',
        bg: 'bg-amber-500/5',
        headerBg: 'bg-amber-500/10',
        categories: ['tax_filing'],
      },
      {
        key: 'banking',
        label: 'Banking',
        icon: 'Landmark',
        color: 'text-rose-400',
        dot: 'bg-rose-400',
        border: 'border-rose-500/25',
        bg: 'bg-rose-500/5',
        headerBg: 'bg-rose-500/10',
        categories: ['investment_update', 'banking_treasury'],
      },
      {
        key: 'payroll',
        label: 'Payroll',
        icon: 'Banknote',
        color: 'text-violet-400',
        dot: 'bg-violet-400',
        border: 'border-violet-500/25',
        bg: 'bg-violet-500/5',
        headerBg: 'bg-violet-500/10',
        categories: ['payroll', 'invoice_reconciliation'],
      },
      {
        key: 'meetings',
        label: 'Meetings',
        icon: 'CalendarClock',
        color: 'text-cyan-400',
        dot: 'bg-cyan-400',
        border: 'border-cyan-500/25',
        bg: 'bg-cyan-500/5',
        headerBg: 'bg-cyan-500/10',
        categories: ['meeting_invitation'],
      },
    ]),
  },

  // ── Sales & Marketing ─────────────────────────────────────────────────────
  sales_marketing: {
    key: 'sales_marketing',
    name: 'Sales & Marketing',
    emoji: '📣',
    lanes: withShared([
      {
        key: 'leads',
        label: 'Leads',
        icon: 'UserPlus',
        color: 'text-blue-400',
        dot: 'bg-blue-400',
        border: 'border-blue-500/25',
        bg: 'bg-blue-500/5',
        headerBg: 'bg-blue-500/10',
        categories: ['lead_inbound', 'prospect_followup'],
      },
      {
        key: 'deals',
        label: 'Deals',
        icon: 'Handshake',
        color: 'text-emerald-400',
        dot: 'bg-emerald-400',
        border: 'border-emerald-500/25',
        bg: 'bg-emerald-500/5',
        headerBg: 'bg-emerald-500/10',
        categories: ['deal_update', 'client_success'],
      },
      {
        key: 'campaigns',
        label: 'Campaigns',
        icon: 'Megaphone',
        color: 'text-amber-400',
        dot: 'bg-amber-400',
        border: 'border-amber-500/25',
        bg: 'bg-amber-500/5',
        headerBg: 'bg-amber-500/10',
        categories: ['campaign_report', 'content_asset'],
      },
      {
        key: 'partners',
        label: 'Partners',
        icon: 'Link2',
        color: 'text-rose-400',
        dot: 'bg-rose-400',
        border: 'border-rose-500/25',
        bg: 'bg-rose-500/5',
        headerBg: 'bg-rose-500/10',
        categories: ['partner_affiliate'],
      },
      {
        key: 'events',
        label: 'Events',
        icon: 'CalendarDays',
        color: 'text-violet-400',
        dot: 'bg-violet-400',
        border: 'border-violet-500/25',
        bg: 'bg-violet-500/5',
        headerBg: 'bg-violet-500/10',
        categories: ['event_webinar', 'tool_crm_notification'],
      },
      {
        key: 'meetings',
        label: 'Meetings',
        icon: 'CalendarClock',
        color: 'text-cyan-400',
        dot: 'bg-cyan-400',
        border: 'border-cyan-500/25',
        bg: 'bg-cyan-500/5',
        headerBg: 'bg-cyan-500/10',
        categories: ['meeting_invitation'],
      },
    ]),
  },
};

// ─── Exports ──────────────────────────────────────────────────────────────────

/** All role configs keyed by role key string. */
export const ROLE_CONFIGS: Record<string, RoleConfig> = ROLE_CONFIGS_MAP;

/**
 * Returns the lane configs for the given role key.
 * Falls back to an empty array if the role is not found.
 */
export function getRoleLanes(roleKey: string): LaneConfig[] {
  return ROLE_CONFIGS[roleKey]?.lanes ?? [];
}
